// Builds an override stylesheet from the Shell's own theme CSS.
//
// GNOME 50's gnome-shell.css never hardcodes the accent. It writes the
// keywords -st-accent-color / -st-accent-fg-color, usually wrapped in St's
// color functions:
//
//     background-color: st-mix(-st-accent-color, st-darken(#fafafb, 7%), 5%);
//
// St already evaluates those functions over literal colors, so we only have to
// swap the two keywords for real values and hand the rules back. Every derived
// shade (hover, active, transparentized) then falls out for free, and nothing
// here is tied to a specific Shell release.

const ACCENT_TOKEN = /-st-accent-color/g;
const ACCENT_FG_TOKEN = /-st-accent-fg-color/g;

function stripComments(css) {
    return css.replace(/\/\*[\s\S]*?\*\//g, '');
}

/**
 * Split a stylesheet into blocks. The Shell's CSS is compiled Sass, so rule
 * bodies are already flat; only at-rules (@media, @keyframes) nest.
 */
function parseNodes(css) {
    const nodes = [];
    let i = 0;
    let preludeStart = 0;

    while (i < css.length) {
        const c = css[i];

        if (c === '{') {
            const prelude = css.slice(preludeStart, i).trim();
            let depth = 1;
            let j = i + 1;
            while (j < css.length && depth > 0) {
                if (css[j] === '{')
                    depth++;
                else if (css[j] === '}')
                    depth--;
                j++;
            }
            nodes.push({prelude, body: css.slice(i + 1, j - 1)});
            i = j;
            preludeStart = j;
            continue;
        }

        // An at-rule with no block, e.g. @import url(...);
        if (c === ';') {
            const statement = css.slice(preludeStart, i).trim();
            if (statement)
                nodes.push({statement});
            i++;
            preludeStart = i;
            continue;
        }

        i++;
    }

    return nodes;
}

function rewriteDeclaration(decl, accent, accentFg, forceImportant) {
    let out = decl.replace(ACCENT_FG_TOKEN, accentFg).replace(ACCENT_TOKEN, accent);
    if (forceImportant && !/!\s*important\s*$/.test(out))
        out += ' !important';
    return out;
}

/**
 * Keep only the declarations that mention an accent keyword, rewritten to
 * literal colors. Source order is preserved so the rules keep cascading
 * against each other exactly as the original theme intended.
 */
function extractAccentRules(css, accent, accentFg, forceImportant, indent = '') {
    const chunks = [];

    for (const node of parseNodes(css)) {
        if (node.statement)
            continue;

        if (node.prelude.startsWith('@')) {
            const inner = extractAccentRules(node.body, accent, accentFg, forceImportant, `${indent}  `);
            if (inner)
                chunks.push(`${indent}${node.prelude} {\n${inner}\n${indent}}`);
            continue;
        }

        const decls = node.body
            .split(';')
            .map(d => d.trim())
            .filter(d => d && d.includes('-st-accent-'))
            .map(d => rewriteDeclaration(d, accent, accentFg, forceImportant));

        if (decls.length) {
            const body = decls.map(d => `${indent}  ${d};`).join('\n');
            chunks.push(`${indent}${node.prelude} {\n${body}\n${indent}}`);
        }
    }

    return chunks.join('\n');
}

/**
 * @param {string[]} sources - raw CSS text of the stylesheets to derive from
 * @param {string} accent - literal color for -st-accent-color
 * @param {string} accentFg - literal color for -st-accent-fg-color
 * @param {boolean} forceImportant
 * @returns {string} the generated stylesheet, or '' if nothing matched
 */
export function buildShellStylesheet(sources, accent, accentFg, forceImportant) {
    const parts = [];
    for (const css of sources) {
        if (!css || !css.includes('-st-accent-'))
            continue;
        const rules = extractAccentRules(stripComments(css), accent, accentFg, forceImportant);
        if (rules)
            parts.push(rules);
    }

    if (!parts.length)
        return '';

    return [
        '/* Generated by More Accent Colors. Do not edit; regenerated on every change. */',
        `/* accent: ${accent}  fg: ${accentFg} */`,
        '',
        ...parts,
        '',
    ].join('\n');
}
