// Recolors libadwaita/GTK apps by dropping named-color overrides into the
// user's GTK config. libadwaita resolves @accent_bg_color / @accent_fg_color /
// @accent_color at draw time, so redefining them is enough; GTK watches
// gtk.css and reloads it live.
//
// We never rewrite the user's gtk.css beyond a single marked @import line, so
// anything they already had in there survives.

import GLib from 'gi://GLib';
import Gio from 'gi://Gio';

import {foregroundFor, standaloneExpr} from './colors.js';

const MARKER = '/* more-accent-colors */';
const GENERATED_NAME = 'more-accent-colors.css';
const GENERATED_HEADER = '/* Generated by More Accent Colors. Do not edit. */';

const VARIANTS = {
    gtk4: {dir: 'gtk-4.0'},
    gtk3: {dir: 'gtk-3.0'},
};

function configDir(variant) {
    return GLib.build_filenamev([GLib.get_user_config_dir(), VARIANTS[variant].dir]);
}

function readText(path) {
    try {
        const [ok, bytes] = GLib.file_get_contents(path);
        return ok ? new TextDecoder().decode(bytes) : null;
    } catch {
        return null;
    }
}

function writeText(path, text) {
    try {
        GLib.mkdir_with_parents(GLib.path_get_dirname(path), 0o755);
        return GLib.file_set_contents(path, text);
    } catch {
        return false;
    }
}

const ownsGeneratedFile = text => text === GENERATED_HEADER ||
    text?.startsWith(`${GENERATED_HEADER}\n`);

function generatedCss(variant, hex, dark) {
    const fg = foregroundFor(hex);

    if (variant === 'gtk3') {
        return [
            GENERATED_HEADER,
            `@define-color theme_selected_bg_color ${hex};`,
            `@define-color theme_selected_fg_color ${fg};`,
            '',
        ].join('\n');
    }

    // libadwaita 1.9 reads the custom properties and keeps the @define-color
    // names as compatibility aliases, so both get set. Overriding
    // --accent-bg-color also re-derives --accent-color on its own, including
    // the dark and OSD variants; the @define-color spelling can't do that, so
    // there it gets libadwaita's formula written out explicitly.
    return [
        GENERATED_HEADER,
        ':root {',
        `    --accent-bg-color: ${hex};`,
        `    --accent-fg-color: ${fg};`,
        '}',
        '',
        `@define-color accent_bg_color ${hex};`,
        `@define-color accent_fg_color ${fg};`,
        `@define-color accent_color ${standaloneExpr(hex, dark)};`,
        '',
    ].join('\n');
}

/** Drop any previously written import line, keeping the user's own content. */
function withoutImport(text) {
    if (!text)
        return '';
    return text
        .split('\n')
        .filter(line => !line.includes(MARKER))
        .join('\n');
}

/**
 * @param {'gtk3'|'gtk4'} variant
 * @param {string} hex - accent color
 * @param {boolean} dark - whether the dark color scheme is active
 */
export function applyGtk(variant, hex, dark) {
    const dir = configDir(variant);
    const generatedPath = GLib.build_filenamev([dir, GENERATED_NAME]);
    const gtkCssPath = GLib.build_filenamev([dir, 'gtk.css']);

    const previousGenerated = readText(generatedPath);
    if (GLib.file_test(generatedPath, GLib.FileTest.EXISTS) &&
        (previousGenerated === null || !ownsGeneratedFile(previousGenerated))) {
        console.warn(`More Accent Colors: refusing to overwrite unowned ${generatedPath}`);
        return false;
    }

    const previousGtkCss = readText(gtkCssPath);
    if (GLib.file_test(gtkCssPath, GLib.FileTest.EXISTS) && previousGtkCss === null) {
        console.warn(`More Accent Colors: could not read ${gtkCssPath}`);
        return false;
    }

    if (!writeText(generatedPath, generatedCss(variant, hex, dark))) {
        console.warn(`More Accent Colors: could not write ${generatedPath}`);
        return false;
    }

    // @import has to come before any rule, so the line always goes on top.
    const existing = withoutImport(previousGtkCss).replace(/^\n+/, '');
    const importLine = `@import url("${GENERATED_NAME}"); ${MARKER}`;
    if (!writeText(gtkCssPath, existing ? `${importLine}\n${existing}` : `${importLine}\n`)) {
        if (previousGenerated === null) {
            try {
                Gio.File.new_for_path(generatedPath).delete(null);
            } catch {
                // Best effort rollback.
            }
        } else {
            writeText(generatedPath, previousGenerated);
        }
        console.warn(`More Accent Colors: could not write ${gtkCssPath}`);
        return false;
    }

    return true;
}

/** Undo applyGtk, leaving the user's own gtk.css content untouched. */
export function clearGtk(variant) {
    const dir = configDir(variant);
    const generatedPath = GLib.build_filenamev([dir, GENERATED_NAME]);
    const gtkCssPath = GLib.build_filenamev([dir, 'gtk.css']);

    const generated = readText(generatedPath);
    if (generated !== null && ownsGeneratedFile(generated)) {
        try {
            Gio.File.new_for_path(generatedPath).delete(null);
        } catch {
            // Already gone.
        }
    }

    const text = readText(gtkCssPath);

    // Nothing of ours in there - leave the user's file completely alone.
    if (text === null || !text.includes(MARKER))
        return;

    const remaining = withoutImport(text);

    if (remaining.trim() === '') {
        // The file only ever held our import line, so we created it.
        try {
            Gio.File.new_for_path(gtkCssPath).delete(null);
        } catch {
            // Already gone.
        }
        return;
    }

    writeText(gtkCssPath, remaining.replace(/^\n+/, ''));
}
